version: "0.2"
words:
  - aioble
  - asyncio
  - direnv
  - dpkg
  - envsubst
  - esptool
  - gattacker
  - isconnected
  - josverl
  - microcontroller
  - microcontrollers
  - micropython
  - mpremote
  - pyenv
  - pyproject
  - pyright
  - rssi
  - Thomasson
  - uasyncio
  - venv
  - WLAN
  - xdigit
